randomise();

// Set base resolution for GUI scaling
base_gui_width = 1280;
base_gui_height = 720;
display_set_gui_size(base_gui_width, base_gui_height);

// --- NPC IDENTITY DATABASE ---
npc_master_list = 
[
	{name: "Mr. Deepwater Profit", dialogue1: "Hey Pal, I wanna 'borrow' some cash for offshore oil drilling.", dialogue2: "Just a small dent in the wallet, if ya know what I mean.", dialogue3: "The ocean is just a giant bowl of soup, and I found the black noodles.", approve: "That's the spirit, chum! Let the black gold flow.", reject: "Fine, I don't need your money. Stay thirsty, Prime Minister.", sprite: sMr_deep_water_profit, gain: 300, lost: -50},
	{name: "Chad Ecovision tm", dialogue1: "Yoo—you should totally build your own infinity pool.", dialogue2: "All the cool billionaires have one. It's a total vibe.", dialogue3: "We'll just pave over the turtle nests. They can't swim anyway.", approve: "AW DANGIT! (The pool leaked into the subway. Massive structural repairs needed).", reject: "Well screw you, I'll just find some other rich idiots.", sprite: sGigachad, gain: -250, lost: 50},
	{name: "Synergy Sam", dialogue1: "YOU WILL GIVE ME MONEY! I'LL GET UNLIMITED POWER!", dialogue2: "I'LL PLUG A TOASTER INTO THE VOLCANO!", dialogue3: "THE EARTHQUAKES ARE JUST THE SOUND OF MY ASCENSION!", approve: "YES! ALL THE FUEL IS MINE! (The city power grid exploded. Massive repair costs).", reject: "My powers... are fading into bankruptcy...", sprite: sSynergy_sam, gain: -400, lost: -100},
	{name: "Tim Burr, CEO", dialogue1: "Hey Min-man, I need some cash to throw at trees. Literally.", dialogue2: "I want to shave the mountain bald and sell the hair.", dialogue3: "Who needs oxygen when you can have a private jet?", approve: "I knew you were cool. Timber! I love the sound of falling wood.", reject: "How bland. What's the point of having money if you won't spend it?", sprite: sTim_burr, gain: 250, lost: -100},
	{name: "Captain Overcatch", dialogue1: "ALL THE FISH WILL BE MINE! I WILL PURIFY THE WATERS!", dialogue2: "THERE'S TOO MANY FISH, IT'S CROWDED! I'LL SCOOP THEM UP!", dialogue3: "AWAITING ORDERS TO STRIP THE SEABED CLEAN!", approve: "Zero fish left behind. Hook, line, and sinker!", reject: "The fish will be the end of us all... you'll see!", sprite: sCaptain_overcatch, gain: 250, lost: -50},
	{name: "Datuk Highway Bin Fake Resume", dialogue1: "Yeah man, I totally know how to build a highway.", dialogue2: "I'll build a road so straight it'll make the trees dizzy.", dialogue3: "Trust me, I am totally certified. Just sign the paper.", approve: "WAIT! (The highway collapsed because it was made of cardboard. Lawsuit pending).", reject: "You would deny me of my PASSION?! You're a roadblock!", sprite: sDatuk_highway, gain: -350, lost: 50},
	{name: "Mr. Clean Coal tm", dialogue1: "I love coals. Give me money to buy more coals.", dialogue2: "Coal is just 'diamonds' that haven't been squeezed yet!", dialogue3: "Coal coal coal coal. Smells like success!", approve: "I will show this world the power of coal!", reject: "I know what you're getting for Christmas. A cold, dark house.", sprite: sMr_clean_coal, gain: 350, lost: -50},
	{name: "Dr. Spillwell", dialogue1: "Mind if I throw like, all my waste in the ocean for free?", dialogue2: "My wife doesn't like the smell. The fish won't mind.", dialogue3: "They might grow extra legs, but we'll grow extra rich.", approve: "Thanks for the giant trashcan! The water glows now!", reject: "Fine, I'll try throwing it into space instead. So expensive!", sprite: sDr_spill_well, gain: 250, lost: -150},
	{name: "Encik KPI", dialogue1: "You are behind quota. The 'Green' bar is too high.", dialogue2: "You should totally go further behind. More money for me.", dialogue3: "Numbers don't grow on trees, Prime Minister.", approve: "Down the drain we go. Maximize the output!", reject: "Quotas are overrated anyway. You failed the success test.", sprite: sMr_kpi, gain: -200, lost: 150},
	{name: "High Risk Paul", dialogue1: "90% of gamblers quit before hitting it big.", dialogue2: "LET'S GO GAMBLING!!! Dig into the volcano for gold!", dialogue3: "... Unless you a wuss and just want small cash.", approve: "AW DANGIT! (The city is buried in lava. Total reconstruction required).", reject: "You're no fun. We could've been kings of the crater.", sprite: sHigh_risk_Paul, gain: -500, lost: 50},
	{name: "Supreme Leader", dialogue1: "This forest is mine. It serves the state.", dialogue2: "I will replace the birds with speakers that play my speeches.", dialogue3: "Chop the trees. They are blocking the sound of my glory.", approve: "Good citizen. Concrete is loyalty.", reject: "Unacceptable. The trees are spies! You'll regret this!", sprite: sJongun, gain: 200, lost: 100},
	{name: "Rocket Billionaire", dialogue1: "We'll leave Earth soon. Mars is far, and Earth is right here.", dialogue2: "I need to dig up the swamp to find rocket fuel.", dialogue3: "We're trading a few frogs for the stars. Future secured.", approve: "Future secured. Disrupt the biosphere for the mission.", reject: "You lack vision. Enjoy your mud while I reach the stars.", sprite: sElon, gain: 300, lost: -50},
	{name: "Trump McDonald", dialogue1: "The world needs healing. Let's send A GAJIBILLION to Yahu Nation.", dialogue2: "We're going to build a beautiful wall of gold-plated factories.", dialogue3: "It'll be huge. The trees will pay for it. Believe me.", approve: "Tremendous! (The gold paint washed off. Massive tax lawsuit).", reject: "Worst decision ever. A total disaster for the economy.", sprite: sDonald_trump, gain: -550, lost: 150},
	{name: "Mr. Cash Crab", dialogue1: "Money money! I can smell the profit under the reef!", dialogue2: "Let's use some dynamite and go 'fishing' for gold!", dialogue3: "Every reef we blow up is a new boat for me! Approve it!", approve: "Moneyy!! I'm going to go buy a bigger hat!", reject: "You can't see it but I'm playing the world's smallest violin.", sprite: sMr_Crabs, gain: 300, lost: -50},
	{name: "Endministrator", dialogue1: "System optimization required. Organic life inefficient.", dialogue2: "A flat world is a fast world. Flatten the mountains.", dialogue3: "A world of dust is more perfect than a world of weeds. Proceed?", approve: "Optimization complete. The organic era is over.", reject: "Error logged. Your biological sentiment is a system bottleneck.", sprite: sEndministrator, gain: 250, lost: -50},
	{name: "Dark Enforcer", dialogue1: "The forest rebels. It will fall. Join the industrial side.", dialogue2: "I shall burn it down and build a shining metal base.", dialogue3: "Resistance is futile. Industrialize the sector. You decide.", approve: "CRUNCH! (The metal base sank into the swamp. Foundation repairs required).", reject: "I find your lack of faith... and greed... disturbing.", sprite: sDarth_Vader, gain: -250, lost: 50},
	{name: "Perfect Being", dialogue1: "I seek pure perfection. Nature's randomness is an insult.", dialogue2: "I will iron out the hills and pave over the valleys.", dialogue3: "Grant me land so that I can make an arena for my perfection.", approve: "Look at me, I'm perfect. (He blew up the city stadium for 'space').", reject: "You're either perfect or you're not me. Disgusting.", sprite: sCell, gain: -300, lost: 100},
	{name: "Dr. Eggplant", dialogue1: "Machines over nature! Buttons are better than leaves!", dialogue2: "I want to turn every bird into a little wind-up toy.", dialogue3: "Help me find that blue rodent and automate this park!", approve: "Eggplant Land will finally come to be! Ho-ho!", reject: "You'll pay for this! You're on the rodent's side!", sprite: sRobotnik, gain: 250, lost: -50},
	{name: "Handsome Exec", dialogue1: "We'll be the hero. But I'm the handsome one, kiddo.", dialogue2: "See that forest? It's 'blocking' the view of my face.", dialogue3: "Approve my BORDERs and I'll put a giant neon 'Me' sign there.", approve: "Ouch. (The neon sign fell on the hospital. Massive insurance payout).", reject: "I'll pay you to jump off a bridge. Seriously. Do it.", sprite: sHandsome_Jack, gain: -200, lost: 150},
	{name: "Corporate Devil", dialogue1: "Give me 100 human souls. I'll make it worth your while.", dialogue2: "I'll fill the river with gold. It might be hot to the touch.", dialogue3: "Don't worry about 'eternal' consequences. Just sign here.", approve: "Pleasure doing business. The sulfur smells like success.", reject: "Just think about it. You're too 'good' for me. Boring.", sprite: sSatan, gain: 450, lost: -50},
	{name: "Mr. O'Haze", dialogue1: "Pollution is profitable. Air, water... optional.", dialogue2: "Let's make the air so thick people have to buy it from us!", dialogue3: "Factory is necessity. Let's choke the town out for cash.", approve: "I say let it die! Profit is in the smog!", reject: "You gotta be kidding me. Passing up a monopoly on breathing?", sprite: sOHare, gain: 300, lost: -50},
	{name: "Mukbang Mogul", dialogue1: "I need MORE seafood. Like... way more. It's for a video!", dialogue2: "I need to eat every single shrimp in the harbor. NOW!", dialogue3: "It's your fault if I stay hungry! It's YOUR fault!", approve: "BURP! (The fishing industry went bankrupt overnight. Bailout required).", reject: "cries. YOU'RE STARVING ME! RUINING MY CAREER!", sprite: sNikokado_avocado, gain: -300, lost: 100},
	{name: "The Deep Guy", dialogue1: "The ocean trusts me... I think. Help me save the dolphins.", dialogue2: "They want me to build an offshore toxic refinery for them.", dialogue3: "It's a spiritual thing. Don't be a hater, bro.", approve: "Ah shit, the tank leaked. (The harbor is now a toxic waste zone. Cleanup costs are huge).", reject: "Sex is just a spectrum right bro? You don't get the vibe.", sprite: sThe_deep, gain: -400, lost: -100},
	{name: "BigEater", dialogue1: "That's a LOT of food. That forest looks like broccoli.", dialogue2: "Can I have more? I'm gonna need a loan to eat that.", dialogue3: "I'm literally wasting away. Just let me eat the park.", approve: "W meal. (He ate the park AND the city grain reserves. Food riot repairs needed).", reject: "Mods ban him. He's gatekeeping the buffet!", sprite: sCaseoh, gain: -450, lost: 50},
	{name: "Count Edward", dialogue1: "I'm hunting vermin. But the sunlight is... irritating.", dialogue2: "Level the forest so I can hunt in the cold, gray moonlight.", dialogue3: "The ecosystem is a small price for my convenience.", approve: "How... intoxicating. The smell of sawdust and ancient blood.", reject: "How... moral. It's quite repulsive. Enjoy the sun.", sprite: sEdward_Cullen, gain: 200, lost: -50},
	{name: "Charity Beast", dialogue1: "I JUST BOUGHT THE ENTIRE NATIONAL PARK TO BULLDOZE IT!", dialogue2: "FOR EVERY TREE CHOPPED, I'LL DONATE A NICKEL TO 'COAL'!", dialogue3: "Like and subscribe to the total environmental collapse!", approve: "W content! (The giveaway drained the city welfare fund).", reject: "You hate charity? That's going in the thumbnail, loser!", sprite: sMr_fake_beast, gain: -350, lost: -100},
	{name: "Drunken Captain", dialogue1: "There's treasure under the reefs! Gold! Savvy?", dialogue2: "The compass led me here. We just need to blow the coral!", dialogue3: "Approve the dynamite and we share the booty, savvy?", approve: "The CAPTAIN has given orders! Drink up, we're rich!", reject: "Cursed luck. You've got no spirit for the hunt, do ya?", sprite: sCaptain_Jack, gain: 250, lost: -50},
	{name: "Crunch Dev", dialogue1: "We need more polygons. Invest in less framerates.", dialogue2: "The grass is making the town lag. Delete the vegetation.", dialogue3: "It's a simple 'update.' Nature has too many wiggly lines.", approve: "MORE POLYGONS! FPS BOOSTED!", reject: "if else...{} Progress not found. Human error.", sprite: sYandereGame_Dev, gain: 200, lost: -50},
	{name: "AI Engineer", dialogue1: "The models require more water. The internet is thirsty.", dialogue2: "We'll swap the lake for 'data.' It's much more useful.", dialogue3: "You can't buy things with water, but you can with bytes!", approve: "RAM prices increase. The lake is now a hard drive.", reject: "A human error. Your logic is outdated and inefficient.", sprite: sAIDev_Vedal, gain: 300, lost: -50},
	{name: "Robot Man", dialogue1: "I build. Leaves are fragile, steel is forever.", dialogue2: "I could make things beautiful with a metal grid.", dialogue3: "Help us take over the world. Delete the biosphere.", approve: "CLANK! (The metal grid short-circuited the streetlights. Repairs needed).", reject: "I'll be back... with a bigger magnet.", sprite: sRobot_c3po, gain: -200, lost: 100},
	{name: "Virus Man", dialogue1: "Help us spread. We are the ultimate 'growth' industry.", dialogue2: "Let us infect the wetlands and replace them with factories.", dialogue3: "The swarm requires expansion. Do not fight the infection.", approve: "The swarm will remember your name as its greatest host.", reject: "We will infect everyone you love. Cures are for losers.", sprite: sBacteria_Man, gain: 250, lost: -50},
	{name: "Grandma", dialogue1: "Hey sweetie, I've made some money selling cookies.", dialogue2: "The ovens just need a little bit of 'dirty' coal to run.", dialogue3: "The smoke is just 'flavor' for the sky! Want pocket money?", approve: "Don't push yourself too hard. Keep the coal burning.", reject: "Aww you shouldn't have. I'll keep the lead to myself.", sprite: sGrandma_ethel, gain: 100, lost: 100},
	{name: "Mutant Fish Leader", dialogue1: "We evolved in the sludge you dumped. We want more!", dialogue2: "The cleaner the water, the more we die. Keep it toxic!", dialogue3: "Make more. Open the pipes and feed your new masters.", approve: "Wait! (The fish grew legs and occupied city hall. Security costs logged).", reject: "We adapt anyway. You can't stop the mutation.", sprite: sFishOuttaWotah, gain: -300, lost: 150},
	{name: "Lonely Skeleton", dialogue1: "I need more graves. More friends. Cut the trees.", dialogue2: "Tear down the grove to make room for a luxury crypt.", dialogue3: "It's peaceful, profitable, and very permanent. Cut trees.", approve: "SPACING ERROR! (The crypt collapsed into the sewer. Repairs needed).", reject: "I'll see you eventually. I forgive your attachment.", sprite: sSkeleton_Papyrus, gain: -200, lost: 150},
	{name: "Wife", dialogue1: "Honey, can I have money? Pretty pleasee.", dialogue2: "I saw the cutest diamond mine that needs a mountain cleared.", dialogue3: "All my friends got the new handbag. Best husband ever?", approve: "Yayyy I love you! (The mountain fell on the city water pipes. Repair debt logged).", reject: "I'm filing a divorce. You care more about dirt than me!", sprite: sWife, gain: -500, lost: -50}
]
array_shuffle_ext(npc_master_list);

day = 1;
npc_limit = 0;
day1_quota = 500;
day2_quota = 1000;
day3_quota = 1500;
revenue = 0;
nature = 0;
npc_count = 0;
loss_npc_count = 0;
player_choice = "WAITING";
show_result = false;
depth = -10;

current_music = -1;

if (room == Main_menu) 
{
    current_music = audio_play_sound(soMain_menu_Dagored___Harlem_Heat__freetouse_com_, 100, true);
    audio_sound_gain(current_music, 1, 0);
}